name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: python
      run: sudo apt-get install python2.7 build-essential ccache g++ gawk git make wget libtool libxml2-dev libxslt1-dev python-dev python-pip python-setuptools python-matplotlib python-serial python-scipy python-opencv python-numpy python-pyparsing xterm lcov gcovr libcsfml-dev libcsfml-audio2.4 libcsfml-dev libcsfml-graphics2.4 libcsfml-network2.4 libcsfml-system2.4 libcsfml-window2.4 libsfml-audio2.4 libsfml-dev libsfml-graphics2.4 libsfml-network2.4 libsfml-system2.4 libsfml-window2.4 python-yaml python3-yaml && pip2 -q install --user -U future lxml pymavlink MAVProxy pexpect pygame
    - name: em
      run: git clone https://github.com/emscripten-core/emsdk.git && cd emsdk && ./emsdk install latest && ./emsdk activate latest && source ./emsdk_env.sh
    - name: src
      run: git clone https://github.com/meee1/ardupilot.git --depth 2 --no-single-branch src     && cd src     && git checkout emscripten  && git submodule update --init --recursive modules/gbenchmark     && git submodule update --init --recursive modules/gtest     && git submodule update --init --recursive modules/mavlink     && git submodule update --init --recursive modules/uavcan     && git submodule update --init --recursive modules/waf
    - name: test
      run: source ./emsdk/emsdk_env.sh && cd src && ./waf configure copter --disable-gccdeps --disable-tests
    - name: art
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: arduwasm
        # Directory containing files to upload
        path: src/build/sitl/bin
